### ISSUE TITLE
Facy force quit after get access token

### ISSUE THREAD

**Issue by knighthedspi** [huydx/facy#29]
Facy force quit after get access token. Error logs are described as below
Fetching facebook stream at first time may take a while ♩ ♪ ♫ ♬

★  goto https://developers.facebook.com/tools/accesstoken/ and enter User access token: 
CAAEZAog7sIr0BAKAch043spWpxzm414BpxtRMnEwPE8B1IHaXjehwRuJK3MGwxDPDZAqldT5M4ERq34Wst6znv1eSug8EJH7hrgFDDiZCI6HLQWf0ItMztLpL3fZAOK854enYhZAV1pZAZAdOWQiZBA6HY3YJgjJr5pL2rs8u1ZCJZCISn6eW02Um2ZAAWpEl4SByicSJJVuZAUNGKFaPX8u9kP1
 f  >> 
[Info] Please restart facy to obtain new access token!

facy going to stop...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1433:in `unlink': No such file or directory - /Users/huytran/.facy_access_token.yml (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1433:in `block in remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1438:in `platform_support'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1432:in `remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:785:in `remove_file'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:563:in `block in rm'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:562:in `rm'
	from /Library/Ruby/Gems/2.0.0/gems/facy-1.2.17/lib/facy/facebook.rb:107:in `expired_session'
	from /Library/Ruby/Gems/2.0.0/gems/facy-1.2.17/lib/facy/facebook.rb:47:in `rescue in facebook_notification_fetch'
	from /Library/Ruby/Gems/2.0.0/gems/facy-1.2.17/lib/facy/facebook.rb:40:in `facebook_notification_fetch'
	from /Library/Ruby/Gems/2.0.0/gems/facy-1.2.17/lib/facy/core.rb:90:in `block (3 levels) in start'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.4/lib/em/timers.rb:56:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.4/lib/em/timers.rb:56:in `fire'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/facy-1.2.17/lib/facy/core.rb:69:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/facy-1.2.17/bin/facy:18:in `<top (required)>'
	from /usr/bin/facy:23:in `load'
	from /usr/bin/facy:23:in `<main>'

Please check and fix this issue ASAP

**Comment by limeless** [comment]
Ive got the same problem too, 
seems like facy is stuck at reput appid and secret to access the facebook,
so It kept telling us to fill that token but it already expired.

is there a way to fix this?

**Comment by limeless** [comment]
@knighthedspi  
I find out remove facy_config.yml can re enter the appid,
'''rm -rf /tmp/.facy_config.yml'''
![screen shot 2015-02-02 at 3 34 56 pm](https://cloud.githubusercontent.com/assets/1501022/5997077/18e906a2-aaf1-11e4-8c7e-f6ff873a55ef.png)

but after reset the appid I still can't pass the token part :(

**Comment by MaxPleaner** [comment]
same problem

**Comment by wheatdog** [comment]
same problem

**Comment by lefoy** [comment]
same here

**Comment by N00D13** [comment]
Same here

**Comment by cyrixhero** [comment]
same problem. I think that is Facebook upgrade API, so we get error :(

**Comment by atuanpham** [comment]
same problem :(

**Comment by huydx** [comment]
sorry for long delay, can you guy do the following step:

```
rm ~/.facy_access_token.yml
rm /tmp/.facy_config.yml
gem uninstall facy
gem install facy
```

**Comment by dottdottdott** [comment]
got the same problem. Deleting confings and reinstall did not help for me.
It looks like something with giving the permissions is not working. If i visit the link:
https://www.facebook.com/dialog/oauth?client_id=#appidhere#&scope=friends_status,manage_notifications,publish_actions,read_friendlists,read_stream,user_status,read_mailbox&redirect_uri=http://www.facebook.com/connect/login_success.html
i get this error:
"Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."
After i click OK, i get a page that just says "success"

**Comment by huydx** [comment]
@dottdottdott success is ok. Because of authentication is now not supported officially by facebook, but it still work. After this step you just type "enter" in the terminal and go to the next step, it should be ok.

**Comment by dottdottdott** [comment]
Ah ok, just thought that there might be the problem, because it also shows me in my facebook settings that the app has only permission to access to public profile and friend list. In the link to grant access it is asking for a lot more.
Anyway after i press enter i and put in the user access token i get same problem like the other guys:
 f  >> 
[Info] Please restart facy to obtain new access token!
facy going to stop...
[Info] Please restart facy to obtain new access token!
facy going to stop...

It looks like its not creating a .facy_access_token.yml in my home directory

**Comment by jscappini** [comment]
Same here.

**Comment by bicepjai** [comment]
same issue

**Comment by bsacharski** [comment]
Still occurs on 1.2.18 - anything I can submit to help tackle this issue?

**Comment by codewisdom** [comment]
Sam issue here as well.

**Comment by huydx** [comment]
As i have tried recently, everything is seem to going well, everybody mind to remove all the token, uninstall, and install again?

**Comment by huydx** [comment]
it seems to be ok now, so i will close the issue, if the same phenomenon keep occurring, i will reopen it later

**Comment by dottdottdott** [comment]
i just reinstalled it and tried it again and still got the same problem:

f >>
[Info] Please restart facy to obtain new access token!
facy going to stop...
[Info] Please restart facy to obtain new access token!
facy going to stop..

**Comment by brunini** [comment]
Same here...

**Comment by huydx** [comment]
@dottdottdott @brunini did you remove the token and try again?

```
rm ~/.facy_access_token.yml
rm /tmp/.facy_config.yml
```

**Comment by dottdottdott** [comment]
yes, i reinstalled it and removed the token. I tried it a few times on 3 different systems (all Debian).
Like a said i the earlier post the ~/.facy_access_token.yml is not there, but i deleted the other one

**Comment by lefoy** [comment]
Also tried again but still not working (on mac)

**Comment by luismmolina** [comment]
same here

**Comment by jasonszhao** [comment]
Same here. `~/.facy_access_token.yml` doesn't even exist. When I am taken to the `https://www.facebook.com/dialog/oauth?....` page, there is a dialog box that says

> Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.


Thanks!

**Comment by limeless** [comment]
-Mac OSX 10.11.4 
-Facy 1.2.18
Still not working.
Same issue :<

**Comment by timhtheos** [comment]
+1

**Comment by AlyBadawy** [comment]
why is this closed if no solution yet?
