### ISSUE TITLE
Supporting sixel for image viewing

### ISSUE THREAD

**Issue by KeenS** [huydx/facy#30]
[sixel](https://en.wikipedia.org/wiki/Sixel) enables you to show beautiful image on terminal.

See Also

[端末エミュレータ - Sixel Graphicsを活用したアプリケーションの御紹介 - Qiita](http://qiita.com/arakiken/items/3e4bc9a6e43af0198e46) (ja)

**Comment by huydx** [comment]
@KeenS I've done it once before but there seems to not many users using terminal which support sixel, so I've choose not to include the feature.
